console.log('Hello again world');
var x;
var x=10;
var y;
var y=5;
var sum;
var sum=x+y;
console.log(x+y);
var difference;
var difference=x-y;
console.log(x-y);
var quotient;
var quotient=(x / y);
console.log(x/y);
var product;
var product=(x*y);
console.log(x*y);
var Hellotxt = 'Hello';
var againtxt = 'again';
var  spacetxt = ' ';
var worldtxt = 'world';
console.log 
(Hellotxt + spacetxt + againtxt + spacetxt + worldtxt);
var string1 = 'My favorite food is';
var string2 = 'Mexican food';
var string3 = string1+spacetxt+string2;
console.log (string3);